<html>
<head>
  <title>{$#title} :: Limb3 shop example application on &#123;&#123;macro&#125;&#125;</title>
  <meta http-equiv='Content-Type' content='text/html; charset=utf-8'/>
  <link rel=stylesheet type="text/css" href="/styles/main.css"/>
</head>
<body>





  <div id="header">
    <div class="center">
      <img src="/images/logo.limb.gif"  width='384' height='46' alt='logo.limb' id='logo'/>
    </div>
  </div>

  <div id="center">

    <div id="wrapper" >

      <div id="container">
        <div id="content">
          <h1>{$#title}</h1>

          {{include file='flash_box.phtml'/}}

          {{slot id='content_zone'/}}
        </div>
      </div>

    <div id="sidebar">
      <div id="navigation">
        <ul>
          <li><a href="/product">Products</a></li>
          <li><a href="/cart">Your Cart</a></li>

          <? if($this->toolkit->getSession()->get('user_id')){ ?>
            <li><a href="/user/orders/">Your Orders</a></li>
          <? }else {?>
          <li><a href="/user/login/">Login please</a></li>

          <?} ?>
        </ul>
      </div>

      <div id="profile">
        <dt>Profile</dt>
        {{include file="user/include/profile_box.phtml"/}}
      </div>



        <div id="category">
            <dt>Categories</dt>
            {{include file="category.phtml"/}}
        </div>




    </div>



      </div>
    </div>
  </div>
</body>
</html>