{{paginate iterator='$this->products' pager='pager'/}}

{{pager id="pager" items="5"}}

Всего товаров : {$total_items}. shown: from <b>{$begin_item_number}</b> to <b>{$end_item_number}</b>

{{pager:first}}<a href="{$href}">first</a>{{/pager:first}}

{{pager:list}}
{{pager:current}}<b><a href="{$href}">{$number}</a></b>{{/pager:current}}
{{pager:number}}<a href="{$href}">{$number}</a>{{/pager:number}}
{{pager:separator}}-{{/pager:separator}}
{{/pager:list}}


{{pager:last}}<a href="{$href}">last</a>{{/pager:last}}


{{/pager}}