<html>
<head>
    <title>{$#title} :: Limb3 shop example application on &#123;&#123;macro&#125;&#125;</title>
    <meta http-equiv='Content-Type' content='text/html; charset=utf-8'/>
    <link rel=stylesheet type="text/css" href="/styles/main.css"/>
</head>
<body>



<form id='category_form' name='category_form' method='post' runat='server'>

        <core:wrap in='title_zone'>Create category</core:wrap>
        <core:wrap in='form_zone'>

            <div class="field">
                <label for="name" runat="server">Name category</label>
                <input type="text" name="name" size="40" title='Title' class='req'/>
            </div>

            <div class='form-buttons'>
                    <input id='edit' type='submit' class='action'  value='Add' runat='client'/>
            </div>

        </core:wrap>

</form>





</body>
</html>