{{wrap with="admin_page_layout.phtml" in="content_zone"}}

<h1>Create property</h1>

{{form id='property_form' name='property_form' method='post'}}

{{label for="property_name"}}Title{{/label}} :
{{input name='property_name' type='text' size='60' title='Title'/}}<br/>

{{input name='node_id' type='hidden' size='60' title='node_id' value='$this->node_id'/}}<br/>

{{input type='submit' value='Create'/}}

{{/form}}



{{list using='$this->property' as='$item'}}
<div class='list'>
    <table>
        <tr>
            <th>Property name</th>
            <th>Action</th>

        </tr>

    {{list:item}}
    <tr>
        <td>{$item.property_name}</td>
        <td><a href='{{route_url params="action:delete_property,id:{$item.id}"/}}'>delete</a></td>
    </tr>



    {{/list:item}}
</table>
    </div>
{{/list}}


{{/wrap}}