{{wrap with="admin_page_layout.phtml" in="content_zone"}}

  {{include file="_admin/selectors.phtml"/}}
  {{include file="_admin_object/actions.phtml"/}}

  <div id="header">
    <h1>Product</h1>
  </div>

  <div id="body">
      <h1>Select category</h1>

      {{tree using="$this->Tree" as="$item" kids_prop="childs" counter="$counter" prefix="1"}}
      <ul>
          {{tree:node}}
          <li>
              {$item.identifier}
              <a href='{{route_url params="action:create_to,id:{$item.id}"/}}'> Select</a>&nbsp;&nbsp;
          </li>
          {{/tree:node}}

          {{tree:empty}}
          Комментарии отсуствуют
          {{/tree:empty}}
      </ul>
      {{/tree}}
  </div>
{{/wrap}}
