<? $this->title = 'Registration'; ?>
{{wrap with="front_page_layout.phtml" in="content_zone"}}

{{form id='register_form' name='register_form' method='post'}}

{{include file='_admin/form_errors.phtml'/}}

<dl class="required field">
    <dt><label for="title">Login:</label></dt>
    <dd>{{input name='login' type='text' title='Login'/}}</dd>
</dl>

<dl class="required field">
    <dt><label for="name">Name:</label></dt>
    <dd>{{input name='name' type='text' title='Name'/}}</dd>
</dl>

<dl class="required field">
    <dt><label for="email">Email:</label></dt>
    <dd>{{input name='email' type='text' title='Email' error_class='error'/}}</dd>
</dl>

<dl class="required field">
    <dt><label for="password">Password:</label></dt>
    <dd>{{input name='password' type='text' title='Password' error_class='error'/}}</dd>
</dl>

<dl class="required field">
    <dt><label for="repeat_password">Repeat password:</label></dt>
    <dd>{{input name='repeat_password' type='text' title='Repeat password' error_class='error'/}}</dd>
</dl>

<dl class="field">
    <dt><label for="address">Delivery address:</label></dt>
    <dd>
        {{textarea name="address" id='address' type="text" title="Delivery address"/}}
    </dd>
</dl>

<hr/>
<input id='register' type='submit' value='Register'/>
{{/form}}
{{/wrap}}
