<div class='tabs'>

  <ul>
    <li id='properties'><a>Свойства</a></li>
  </ul>

  <div id="tab_properties">
    
      
        <dl class="field">
          <dt>{{label for="title"}}title:{{/label}}</dt>
          <dd>{{input id="title" name="title" type="text" title="title"/}}</dd>
        </dl>
      
        <dl class="field">
          <dt>{{label for="description"}}description:{{/label}}</dt>
          <dd>{{wysiwyg id="description" name="description" width="100%" height="300px" title="description"/}}</dd>
        </dl>
      
        <dl class="field">
          <dt>{{label for="is_available"}}is_available:{{/label}}</dt>
          <dd>{{js_checkbox id="is_available" name="is_available"/}}</dd>
        </dl>
      
        <dl class="field">
          <dt>{{label for="price"}}price:{{/label}}</dt>
          <dd>{{input id="price" name="price" type="text" title="price"/}}</dd>
        </dl>
      
        <dl class="field">
          <dt>{{label for="image_name"}}image_name:{{/label}}</dt>
          <dd>{{input id="image_name" name="image_name" type="text" title="image_name"/}}</dd>
        </dl>
      
    
  </div>

</div>